### ISSUE TITLE
sh install_db_linux.sh error

### ISSUE THREAD

**Issue by rowbot1** [nicolas-carolo/houndsploit#2]
## Expected Behavior
installation of houndsploit

## Actual Behavior
when runing sh install_db_linux.sh I get this error:
```
install_db_linux.sh: 9: [: Linux: unexpected operator
ERROR: This installation script is only for systems running a Linux distribution
```
git clone https://github.com/nicolas-carolo/houndsploit
cd houndsploit
sh install_db_linux.sh

I needed to remove the `sh`

**Comment by nicolas-carolo** [comment]
Thanks for the report. I will update the installation guide.
